In [1]:
import numpy as np

In [2]:
def swap_rows(A, i, j):
    A[[i,j]] = A[[j, i]]
    return A


In [3]:
M = np.array([
[1, 3, 6],
[0, -5, 2],
[-4, 5, 8]
])
print(M)

[[ 1  3  6]
 [ 0 -5  2]
 [-4  5  8]]


In [4]:
swap_rows(M, 0, 2)

array([[-4,  5,  8],
       [ 0, -5,  2],
       [ 1,  3,  6]])

In [5]:
M_swapped = swap_rows(M, 0, 2)
print(M_swapped)

[[ 1  3  6]
 [ 0 -5  2]
 [-4  5  8]]


In [10]:
M

array([[ 1,  3,  6],
       [ 0, -5,  2],
       [-4,  5,  8]])

In [ ]:
M[:,1] # M[accessing rows, accessing columns]

array([ 3, -5,  5])

In [17]:
c = M[:, 2]

In [19]:
value = enumerate(c)

In [21]:
for i, j in value:
    print(f"Index: {i}, Value: {j}")

Index: 0, Value: 6
Index: 1, Value: 2
Index: 2, Value: 8


In [27]:
np.isclose(0.00001, 0, atol = 1e-5) # instead of checking if 6 == 0
# we check if 6 is close to 0 within a certain tolerance (1e-5 in this case)
# what is isclose()?
# isclose() is a function in the numpy library that checks if two values 
# are close to each other within a specified tolerance. It returns True if 
# the values are close and False otherwise. The function takes three parameters: 
# the first two are the values to compare, and the third is the absolute tolerance 
# (atol) which defines how close the values need to be to be considered equal.
# In the context of checking if a value is effectively zero, we can use 
# np.isclose(value, 0, atol=1e-5) to determine if the value is close enough to zero, 
# accounting for any small numerical inaccuracies that may arise in computations.

True

In [28]:
np.isclose(0.0001, 0, atol = 1e-5)

False

In [49]:
def first_nonzero_column(Mat, col, starting_row):
    col_values = Mat[starting_row:, col]

    for i, value in enumerate(col_values):
        if not np.isclose(value,0, atol = 1e-5):
            return i+starting_row # return the index of the first non-zero row in the specified column, starting from the given row index.
    return -1



In [50]:
M

array([[ 1,  3,  6],
       [ 0, -5,  2],
       [-4,  5,  8]])

In [51]:
N = np.array([
[0, 5, -3 ,6 ,8],
[0, 6, 3, 8, 1],
[0, 0, 0, 0, 0],
[0, 0, 0 ,0 ,7],
[0, 2, 1, 0, 4]
]
)
print(N)

[[ 0  5 -3  6  8]
 [ 0  6  3  8  1]
 [ 0  0  0  0  0]
 [ 0  0  0  0  7]
 [ 0  2  1  0  4]]


In [52]:
print(first_nonzero_column(N, 0, 0))

-1


In [53]:
print(first_nonzero_column(N, 4, 2)) # should return None since all values in the first column are zero

3


In [54]:
print(first_nonzero_column(N, 1, 2))

4


In [55]:
def first_nonzero_row(A, row, augmented = False):
    M = A.copy()
    if augmented:
        M = M[:, :-1] # Exclude the last column (augmented part)

    row_values = M[row, :]

    for i, value in enumerate(row_values):
        if not np.isclose(value, 0, atol = 1e-5):
            return i # return the index of the first non-zero column in the specified row.
    return -1


In [56]:
print(N)

[[ 0  5 -3  6  8]
 [ 0  6  3  8  1]
 [ 0  0  0  0  0]
 [ 0  0  0  0  7]
 [ 0  2  1  0  4]]


In [57]:
first_nonzero_row(N,2)

-1

In [58]:
first_nonzero_row(N, 3)

4

In [59]:
def augmented_matrix(A, B):
    augmented_M = np.hstack((A,B))
    return augmented_M

In [60]:
A = np.array([[1,2,3], [3,4,5], [4,5,6]])
B = np.array([[1], [5], [7]])

print(augmented_matrix(A, B))

[[1 2 3 1]
 [3 4 5 5]
 [4 5 6 7]]


In [61]:
A = np.array([[1,2,3],[0,1,0], [0,0,5]])
B = np.array([[1], [2], [4]])
augmented_M = augmented_matrix(A, B)

In [62]:
augmented_M

array([[1, 2, 3, 1],
       [0, 1, 0, 2],
       [0, 0, 5, 4]])

In [63]:
det_A = np.linalg.det(A)

In [64]:
det_A

4.999999999999999

In [65]:
if np.isclose(det_A, 0, atol = 1e-5):
    print("The matrix A is singular, and the system may have no solution or infinitely many solutions.")
else:
    print("The matrix A is non-singular, and the system has a unique solution.")

The matrix A is non-singular, and the system has a unique solution.
