In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [3]:
a = np.array ([[-1,3],[3,2]],dtype=float) # Coefficients of the system of equations
b = np.array ([7,1],dtype=float) # Constants on the right-hand side

print("Coefficient matrix A:", a)
print("Constants vector b:", b)

Coefficient matrix A: [[-1.  3.]
 [ 3.  2.]]
Constants vector b: [7. 1.]


In [ ]:
# assuming the system of equations is: -1*x1 + 3*x2 = 7 and 3*x1 + 2*x2 = 1
#we can solve the system of equations using numpy's linear algebra solver
solution = np.linalg.solve(a, b)
print("Solution (x1, x2):", solution)

Solution (x1, x2): [-1.  2.]


In [6]:
# we can also find the determinant of the coefficient matrix to check if the system has a unique solution
det = np.linalg.det(a)
print("Determinant of A:", det)

Determinant of A: -11.000000000000002


In [8]:
A_system = np.hstack((a, b.reshape(2, 1))) # Augmented matrix [A|b]
print("Augmented matrix [A|b]:\n", A_system)

Augmented matrix [A|b]:
 [[-1.  3.  7.]
 [ 3.  2.  1.]]


In [9]:
A_system[1]

array([3., 2., 1.])

In [14]:
A_2 = np.array([[-1,3], [3, -9]], dtype=float) # Coefficient matrix with the second column replaced by b

b_2= np.array([7, 1], dtype=float) # Constants vector

d_2 = np.linalg.det(A_2)

print("Determinant of A_2:", np.round(d_2))

Determinant of A_2: -0.0


In [15]:
try:
    solution_2 = np.linalg.solve(A_2, b_2)
    print("Solution for A_2 (x1, x2):", solution_2)
except np.linalg.LinAlgError:
    print("The system of equations has no unique solution.")

Solution for A_2 (x1, x2): [1.32105589e+17 4.40351964e+16]


In [18]:
A_2_system = np.hstack((A_2, b_2.reshape(2, 1))) # Augmented matrix [A_2|b_2]   
A_2_system

array([[-1.,  3.,  7.],
       [ 3., -9.,  1.]])