In [1]:
import numpy as np

In [2]:
A = np.array([[4, 9, 9], [9, 1, 6], [9, 2, 3]])
print("Matrix A (3 by 3):\n", A)

B = np.array([[2, 2], [5, 7], [4, 4]])
print("Matrix B (3 by 2):\n", B)

Matrix A (3 by 3):
 [[4 9 9]
 [9 1 6]
 [9 2 3]]
Matrix B (3 by 2):
 [[2 2]
 [5 7]
 [4 4]]


In [3]:
# we multiply two matrices using A and B 

np.matmul(A, B) # this is the same as A @ B

array([[ 89, 107],
       [ 47,  49],
       [ 40,  44]])

In [ ]:
A @ B # this is the same as np.matmul(A, B) we use @ for dot product and matrix multiplication in numpy

array([[ 89, 107],
       [ 47,  49],
       [ 40,  44]])

In [5]:
# the matmul is only valid when the number of columns in the first matrix (A) matches the number of rows in the second matrix (B).
# In this case, A has 3 columns and B has 3 rows, so the multiplication is valid. The resulting matrix will have dimensions equal 
# to the number of rows of the first matrix (A) and the number of columns of the second matrix (B), which is 3 by 2.

try:
    B@A
except ValueError as e:
    print("Error:", e)

Error: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)


In [6]:
B

array([[2, 2],
       [5, 7],
       [4, 4]])

In [7]:
B.shape

(3, 2)

In [18]:
x = np.array([[1, -2, -5]]) # makes it a 2D array with shape (1, 3) - 1X3
#but this is a 1D array with shape (3,) - 1X3 or (3,) both are the same for 1D arrays
x = np.array([1, -2, -5]) # this is a 1D array with 3 elements, so its shape is (3,) - 1X3 or (3,) both are the same for 1D arrays
y = np.array([4, 3, -1])

In [15]:
x.shape # this is a 1D array with 3 elements, so its shape is (3,) - 1X3 or (3,) both are the same for 1D arrays
# y.shape # this is also a 1D array with 3 elements, so its shape is (3,) - 1X3 or (3,) both are the same for 1D arrays

(1, 3)

In [12]:
z = np.array([[1],[2],[-5]])
z.shape

(3, 1)

In [19]:
z.ndim

2

In [20]:
x.ndim

1

In [21]:
x=np.array([[1, -2, -5]])

In [22]:
x.ndim

2

In [23]:
x = np.array([1,2,3])
x.ndim

1

In [26]:
x = x.reshape(3,1) # this reshapes the 1D array into a 2D array with 3 rows and 1 column (3 by 1) - column vector

In [27]:
x.shape

(3, 1)

In [28]:
A

array([[4, 9, 9],
       [9, 1, 6],
       [9, 2, 3]])

In [29]:
B

array([[2, 2],
       [5, 7],
       [4, 4]])

In [30]:
np.matmul(A,B)

array([[ 89, 107],
       [ 47,  49],
       [ 40,  44]])

In [31]:
np.dot(A,B) # this is the same as np.matmul(A,B) and A @ B

array([[ 89, 107],
       [ 47,  49],
       [ 40,  44]])

In [ ]:
#because of broadcasting rules, we can also do element-wise multiplication of A and B if they 
# have the same shape or if one of them can be broadcasted to the shape of the other. 
# However, in this case, A is 3 by 3 and B is 3 by 2, so they cannot be directly multiplied
#  element-wise without reshaping or broadcasting.