In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3])

In [3]:
np.arange(0,25,5)

array([ 0,  5, 10, 15, 20])

In [ ]:
np.linspace(1,10,5) # 1 to 10, 5 numbers equally spaced and the default type is float that is why we get 1.0, 3.25, 5.5, 7.75, 10.0

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [5]:
# we can change the default type to int by using dtype parameter

np.linspace(1,10,5, dtype=int)

array([ 1,  3,  5,  7, 10])

In [7]:
#same goes for arange as well
np.arange(0,25,5, dtype=float)

array([ 0.,  5., 10., 15., 20.])

In [8]:
a = np.array(['hi'])

In [ ]:
a.dtype # <U2 means unicode string of length 2, that is why we get <U2 because 'hi' has 2 characters

dtype('<U2')

In [10]:
a = np.array(['jai shree ram'])

In [ ]:
a.dtype # see the length of the string is 14, that is why we get <U14 because 'jai shree ram' has 14 characters including spaces

dtype('<U13')

In [12]:
np.zeros(5) # creates an array of 5 zeros

array([0., 0., 0., 0., 0.])

In [13]:
np.ones(5) # creates an array of 5 ones

array([1., 1., 1., 1., 1.])

In [14]:
np.empty(5) # creates an array of 5 uninitialized values, the values can be anything, it is not guaranteed to be zeros or ones, it can be any random values that are present in the memory at that time

array([1., 1., 1., 1., 1.])

In [15]:
np.random.rand(5) # creates an array of 5 random values between 0 and 1

array([0.04797606, 0.25151032, 0.18026454, 0.83033755, 0.52780951])

In [ ]:
np.empty(5) #see how it is giving what is left in the memory, it is not guaranteed to be zeros or ones, it can be any random values that are present in the memory at that time

array([0.04797606, 0.25151032, 0.18026454, 0.83033755, 0.52780951])

In [17]:
# lets create a 2D array
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
# but can we build a 2d array with arange or linspace? yes we can, we just need to reshape it
np.arange(0,25,5).reshape(5,1) # reshape it to 5 rows and 1 column

array([[ 0],
       [ 5],
       [10],
       [15],
       [20]])

In [22]:
np.linspace(0,10,10).reshape(5,2) # reshape it to 5 rows and 2 columns

array([[ 0.        ,  1.11111111],
       [ 2.22222222,  3.33333333],
       [ 4.44444444,  5.55555556],
       [ 6.66666667,  7.77777778],
       [ 8.88888889, 10.        ]])

In [ ]:
# for linspace and arange the (this is initilal, final, number of elements) and for reshape it is (number of rows, number of columns)

In [23]:
np.arange(1,7,1).reshape(2,3) # reshape it to 2 rows and 3 columns

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
#for arange the arguments are (initial, final, step) but for final it is 
# exclusive that is why we get 1,2,3,4,5 and not 6 because 6 is exclusive

#but for linspace the arguments are (initial, final, number of elements) and 
# for final it is inclusive that is why we get 1.0, 3.25, 5.5, 7.75, 10.0 because 10 is inclusive

In [25]:
finddim = np.arange(1,7,1).reshape(2,3)

In [ ]:
finddim.shape # to find the shape of the array, it will give us (2,3) because it has 2 rows and 3 columns

(2, 3)

In [ ]:
finddim.size # to find the total number of elements in the array, it will give us 6 because it has 6 elements in total

6

In [ ]:
finddim.ndim # number of dimensions, in this case it is 2 because it is a 2D array

2

In [30]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[7,8,9],[10,11,12]])

print(arr1+arr2) # element wise addition
print()
print(arr1-arr2) # element wise subtraction
print()
print(arr1*arr2) # element wise multiplication
print()
print(arr1/arr2) # element wise division


[[ 8 10 12]
 [14 16 18]]

[[-6 -6 -6]
 [-6 -6 -6]]

[[ 7 16 27]
 [40 55 72]]

[[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


In [31]:
# when you multiply a vector with a scalar it is called broadcasting, 
# it is a powerful mechanism that allows numpy to work with arrays of
#  different shapes during arithmetic operations. The smaller array is "broadcast" 
# across the larger array so that they have compatible shapes. This is useful when you want to 
# perform operations on arrays of different sizes without having to manually reshape them. 

arr1*2 # broadcasting, it will multiply each element of arr1 by 2


array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [32]:
#indexing and slicing in 2D arrays

a = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [ ]:
# to get 8 we can do, the indexing starts from 0, so for 2nd row it is index 1 and for 1st column it is index 0, so we can do
a[2][1] # 2nd row and 1st column, it will give us 8

8

In [39]:

a1 = np.array([[1,2,3],[4,5,6]])
a2 = np.array([[7,8,9],[10,11,12]])

print(a1)
print()
print(a2)

[[1 2 3]
 [4 5 6]]

[[ 7  8  9]
 [10 11 12]]


In [40]:
# lets learn about stacking and splitting of arrays in numpy, it is a very important concept in numpy, it allows us to
#  combine multiple arrays into a single array or to split a single array into multiple arrays. 
# This is useful when we want to perform operations on multiple arrays or when we want to split an array 
# into smaller arrays for easier processing.
# we can stack these two arrays vertically using vstack
vstacked = np.vstack((a1,a2))

In [41]:
vstacked # it will give us a new array with 4 rows and 3 columns, the first 2 rows are from a1 and the next 2 rows are from a2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [42]:
# we can also stack these two arrays horizontally using hstack
hstacked = np.hstack((a1,a2))
hstacked # it will give us a new array with 2 rows and 6 columns, the first 3 columns are from a1 and the next 3 columns are from a2

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])